--- 
- 'FILE64'
- 'fd_set'
- 'st_table_entry'
- 'rb_atomic_t'
- 'pointer'     
- 'hdr'
- 'C_block'
- 'USTR'
- 'sFILE'
- 'stack_node'
- 'U'
- 'Bigint'
- 'unsigned_time_t'
- 'VALUE'
- 'ID'
- 'RUBY_DATA_FUNC'
- 'ruby_glob_func'
- 'rb_nativethread_t'
- 'mbc_startpos_func_t'
- 'conftest_type'
- 'Regexp'
- 'pid_t'
- 'sigset_t'
- 'regex_t'
- 're_pattern_buffer'
- 'regoff_t'
- 'regmatch_t'
- 'Real'
- 'uint8_t'
- 'uint32_t'               
- 'uint64_t'
- 'rb_digest_hash_init_func_t'
- 'rb_digest_hash_update_funct_t'
- 'rb_digest_hash_finish_funct_t'
- 'MD5_CTX'
- 'RMD160_CTX'
- 'CHAR64LONG16'
- 'SHA1_CTX'
- 'sha2_byte'
- 'sha2_word32'
- 'sha2_word64'
- 'SHA256_CTX'
- 'SHA512_CTX'
- 'SHA384_CTX'
- 's_voidp'
- 's_short'
- 's_int'
- 's_long'
- 's_float'
- 's_double'
- 'freefunc_t'
- 'ANY_TYPE'
- 'callback1_t'
- 'nkf_char'
- 'bfk_nfchar'
- 'conftest_type'
- 'd2i_of_void'               
- 'ossl_asn1_info_t'
- 'DBM'
- 'FILE'
- 'datum'
- 'YYSTYPE'
- 'yysigned_char'
- 'bytestring_t'
- 'SyckNode'
- 'SyckParser'
- 'SyckIoFile'
- 'SyckIoStr'
- 'SyckLevel'
- 'SyckNodeHandler'
- 'SyckErrorHandler'
- 'SyckBadAnchorHandler'
- 'SyckIoFileRead'
- 'SyckIoStrRead'
- 'SyckEmitter'
- 'SyckEmitterNode'
- 'SyckOutputHandler'
- 'SyckEmitterHandler'
- 'bytestring_t'
- 'yamlbyte_utf8_t'
- 'yamlbyte_utf16_t'           
- 'yamlbyte_char_t'
- 'yamlbyte_consumer_t'
- 'yamlbyte_producer_t'
- 'yamlbyte_result_t'
- 'yamlbyte_buff_t'
- 'yamlbyte_inst_t'
- 'yamlbyte_pull_t'
- 'yamlbyte_pushbuff_t'
- 'yamlbyte_pullbuff_t'
- 'Entry'
- 'List'
- 'Mutexv'
- 'ConditionVariable'
- 'legacy_wait_args'
- 'Queue'
- 'DL_HANDLE'
- 'CallFrame'
- 'DummyInterp'
- 'time_t'
- '_fsize_t'
- 'intptr_t'
- 'SIGHANDLER'
- 'sighandler_t'
- 'dev_t'
- 'ino_t'
- 'mode_t'
- 'clock_t'
- 'ptrdiff_t'
- 'off_t'
- 'u_char'
- 'u_short'
- 'caddr_t'
- 'transitionTime'
- 'va_list'
- 'mbc_startpos_func_t'
- 'DIR'
- 'sighandler_t'                  
- 'NODE'
- 'rb_event_t'
- 'rb_event_hook_func_t'
- 'rb_jmpbuf_t'
- 'rb_thread_t'                  
- 'event_hook'
- 'foobazzz'               
- 'DWORD'
- 'size_t'
- 'USTR'
- 'RVALUE'
- '__uint16_t'
- '__int32_t'
- '__uint32_t'
- 'uid_t'
- 'gid_t'
- 'blkcnt_t'
- 'blksize_t'
- '__int64_t'
- 'nlink_t'
- 'stack_type'        
- 'st_data_t'
- 'st_table' 
- 'BDIGITv